# Generated by Django 5.0.6 on 2024-07-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://via.placeholder.com/150', upload_to=None, verbose_name=''),
            preserve_default=False,
        ),
    ]
